#!/bin/bash

echo "🚀 Render Deployment Helper"
echo "============================"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}✅ Code is already pushed to GitHub${NC}"
echo "   Repository: https://github.com/dhwebservices/commandai"
echo "   Branch: main"
echo ""

echo -e "${YELLOW}📋 Next Steps (Manual - via Render Dashboard):${NC}"
echo ""
echo "1. Go to Render Dashboard:"
echo "   👉 https://dashboard.render.com/"
echo ""
echo "2. Check if 'comandr-api' service exists:"
echo "   - If YES: Click the service → 'Manual Deploy' → 'Deploy latest commit'"
echo "   - If NO: Continue to step 3"
echo ""
echo "3. Create new service (if needed):"
echo "   - Click 'New +' → 'Blueprint'"
echo "   - Connect GitHub repository: dhwebservices/commandai"
echo "   - Render will detect render.yaml"
echo "   - Click 'Apply'"
echo ""
echo "4. Add Secret Environment Variables:"
echo "   Go to service → Environment → Add:"
echo ""
echo "   SUPABASE_ANON_KEY="
echo "   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubW13cXJlenNwZ2pzcGRsbHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1OTk1NTIsImV4cCI6MjA5OTE3NTU1Mn0.npTAZwcjLOVkrvLBbOavN8y4QKjmHouIqQcACElnskM"
echo ""
echo "   SUPABASE_SERVICE_ROLE_KEY="
echo "   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubW13cXJlenNwZ2pzcGRsbHpiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MzU5OTU1MiwiZXhwIjoyMDk5MTc1NTUyfQ.qTy4JqM8XS4kzSJjIrg68s9RMRyh0VauHGndu7xmYtY"
echo ""
echo "   JWT_SECRET="
echo "   $(openssl rand -base64 32 2>/dev/null || echo "generate_random_string_here")"
echo ""
echo "5. Wait for deployment (3-5 minutes)"
echo ""
echo "6. Test your API:"
echo "   Once deployed, test at: https://comandr-api.onrender.com/v1/health"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}📝 After Deployment:${NC}"
echo ""
echo "Tell me your Render URL (e.g., https://comandr-api.onrender.com)"
echo "and I'll update the desktop apps to use it!"
echo ""
echo "Then we'll rebuild:"
echo "  npm run build -- --mac --win"
echo ""
echo "And you'll have production-ready installers! 🎉"
echo ""
