import { AgentAuthRepository } from "./agent-auth.repository";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { PeerCertificate } from "node:tls";

/**
 * Agent enrollment service: handles token exchange for new agent registration.
 * Per RFC-001, this is called ONCE per agent on first connection, exchanging
 * a short-lived enrollment token for a long-lived mTLS credential.
 */
export class EnrollmentService {
  constructor(
    private readonly repo: AgentAuthRepository,
    private readonly supabase: SupabaseClient,
  ) {}

  /**
   * Exchange enrollment token for agent credential.
   * Called by agent on first connection with:
   * - tokenId (from tenant admin)
   * - tokenSecret (from tenant admin, shown once)
   * - client certificate (generated by agent, presented via mTLS)
   *
   * Returns the issued AgentCredential. From this point forward, agent
   * authenticates via mTLS client cert only (no bearer tokens).
   */
  async enrollAgent(
    tokenId: string,
    tokenSecret: string,
    clientCert: PeerCertificate,
  ): Promise<{ agentId: string; tenantId: string }> {
    // 1. Verify and consume enrollment token (single-use)
    const token = await this.repo.consumeEnrollmentToken(tokenId, tokenSecret);

    // 2. Extract certificate details
    const certFingerprint = extractFingerprint(clientCert);
    const certSubject = formatCertSubject(clientCert);
    const certExpiresAt = new Date(clientCert.valid_to);

    // 3. Issue long-lived credential tied to this cert
    const credential = await this.repo.issueCredential(
      token.tenantId,
      certFingerprint,
      certSubject,
      certExpiresAt,
      30, // 30-day rotation by default
    );

    return {
      agentId: credential.agentId,
      tenantId: credential.tenantId,
    };
  }
}

function extractFingerprint(cert: PeerCertificate): string {
  if (cert.fingerprint256) {
    return cert.fingerprint256.replace(/:/g, "").toLowerCase();
  }
  if (cert.raw) {
    const crypto = require("crypto");
    return crypto.createHash("sha256").update(cert.raw).digest("hex");
  }
  throw new Error("Cannot extract certificate fingerprint");
}

function formatCertSubject(cert: PeerCertificate): string {
  const subject = cert.subject;
  return Object.entries(subject)
    .map(([key, value]) => `${key}=${value}`)
    .join(", ");
}
